[package]
name = "arc-rs"
version = "0.2.0"
authors = ["192607617@qq.com"]
edition = "2018"
description = "..."
repository = "https://github.com/Moe-Net/arc-rs"
license = "MPL-2.0"

[dependencies]
arc-pest = {version = "0.2", path = "../arc-pest"}
arc_ast = {version = "0.3", path = "../arc-ast"}