[workspace]

default-members = [
    "projects/serde-arc",
    "projects/arc-parser",
    "projects/arc-fmt",
    "projects/arc-number",
]
members = ["projects/*"]

[profile.release]
lto = true
opt-level = "s"
