[package]
name = "serde_arc"
version = "1.0.0"
authors = ["192607617@qq.com"]
edition = "2018"
description = "..."
repository = "https://github.com/Moe-Net/arc-rs"
license = "MPL-2.0"


[dependencies]
text-utils = "0.2.1"

[dev-dependencies]

[features]
