[package]
name = "arc_number"
version = "1.0.0"
authors = ["192607617@qq.com"]
edition = "2018"
description = "..."
repository = "https://github.com/Moe-Net/arc-rs"
license = "MPL-2.0"

[dependencies]
serde = "1.0"
num = "0.3"
bigdecimal = "0.2"

[dev-dependencies]
