[package]
name = "arc_ast"
version = "0.3.0"
authors = ["Aster <galaster@foxmail.com>"]
description = "Arc Readable Configuration Parser via Pest"
license = "MPL-2.0"
readme = "README.md"
repository = "https://github.com/Moe-Net/arc-rs"
exclude = ["/tests/*"]
edition = "2018"


[dependencies]
# serde = "1.0"
serde_json = {version = "1.0", optional = true}
num = "0.3"
indexmap = "1.6"
bigdecimal = "0.2"
toml = "0.5"
serde_yaml = "*"
toml_edit = "*"


[features]
default = ["convert"]
convert = ["json"]
json = ["serde_json"]