[package]
authors = ["192607617@qq.com"]
description = "..."
edition = "2018"
license = "MPL-2.0"
name = "arc_ast"
repository = "https://github.com/Moe-Net/arc-rs"
version = "0.2.0"

[dependencies]
serde = "1.0.114"
# serde_derive = "^1.0.104"
# serde_json = "^1.0.45"
arc_number = {path = "../arc-number", version = "0.1.0"}
linked-hash-map = "0.5.2"

[dev-dependencies]

[features]
