[package]
name = "arc-fmt"
version = "0.1.0"
authors = ["192607617@qq.com"]
edition = "2018"
description = "..."
repository = "https://github.com/Moe-Net/arc-rs"
license = "MPL-2.0"


[dependencies]
textwrap = "0.11"
arc-pest = {path = "../arc-pest",version = "0"}

[dev-dependencies]

[features]
