[package]
name = "arc_convert_lib"
version = "1.0.0"
authors = ["192607617@qq.com"]
edition = "2018"
description = "..."
repository = "https://github.com/Moe-Net/arc-rs"
license = "MPL-2.0"


[dependencies]
textwrap = "0.11"

[dev-dependencies]

[features]
